// prism-angular/src/app/components/ui/post-card.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { UserCacheService } from '../../services/user-cache.service';
import { formatDistanceToNow } from 'date-fns';
import { LucideAngularModule, Heart, MessageCircle, Send, Bookmark, MoreHorizontal } from 'lucide-angular';

@Component({
  selector: 'app-post-card',
  standalone: true,
  imports: [CommonModule, RouterLink, LucideAngularModule],
  templateUrl: './post-card.component.html',
})
export class PostCardComponent implements OnInit {
  @Input() post: any;
  author: any = null;
  timeAgo: string = 'Just now';

  // Icons
  HeartIcon = Heart;
  MessageCircleIcon = MessageCircle;
  SendIcon = Send;
  BookmarkIcon = Bookmark;
  MoreHorizontalIcon = MoreHorizontal;

  constructor(private userCache: UserCacheService) {}

  ngOnInit() {
    this.fetchAuthor();
    if (this.post?.createdAt?.toDate) {
      this.timeAgo = formatDistanceToNow(this.post.createdAt.toDate(), { addSuffix: true });
    }
  }

  async fetchAuthor() {
    if (!this.post?.authorId) return;
    const data = await this.userCache.getUserData(this.post.authorId);
    if (data) {
      this.author = data;
    }
  }
}

<div class="bg-white dark:bg-black border-b border-gray-200 dark:border-gray-800 md:border md:rounded-sm md:mb-6 max-w-lg mx-auto" *ngIf="post">
  <!-- Header -->
  <div class="flex items-center justify-between p-3">
    <a [routerLink]="'/profile/' + post.authorId" class="flex items-center space-x-3">
      <img
        [src]="author?.photoURL || 'https://api.dicebear.com/7.x/avataaars/svg?seed=' + post.authorId"
        [alt]="author?.username || 'User'"
        class="w-8 h-8 rounded-full object-cover border border-gray-200 dark:border-gray-800"
      />
      <span class="font-semibold text-sm">{{ author?.username || 'loading...' }}</span>
    </a>
    <button class="p-1">
      <lucide-icon [name]="MoreHorizontalIcon" [size]="20"></lucide-icon>
    </button>
  </div>

  <!-- Image -->
  <div class="relative w-full bg-gray-100 dark:bg-gray-900 flex items-center justify-center min-h-[300px]">
    <img
      [src]="post.imageUrl"
      [alt]="post.caption || 'Post'"
      class="w-full h-auto max-h-[600px] object-contain"
      loading="lazy"
    />
  </div>

  <!-- Actions -->
  <div class="p-3">
    <div class="flex items-center justify-between mb-3">
      <div class="flex items-center space-x-4">
        <button class="hover:text-gray-500 transition-colors">
          <lucide-icon [name]="HeartIcon" [size]="24" class="stroke-[1.5px]"></lucide-icon>
        </button>
        <a [routerLink]="'/post/' + post.id" class="hover:text-gray-500 transition-colors">
          <lucide-icon [name]="MessageCircleIcon" [size]="24" class="stroke-[1.5px]"></lucide-icon>
        </a>
        <button class="hover:text-gray-500 transition-colors">
          <lucide-icon [name]="SendIcon" [size]="24" class="stroke-[1.5px]"></lucide-icon>
        </button>
      </div>
      <button class="hover:text-gray-500 transition-colors">
        <lucide-icon [name]="BookmarkIcon" [size]="24" class="stroke-[1.5px]"></lucide-icon>
      </button>
    </div>

    <!-- Likes -->
    <div class="font-semibold text-sm mb-1">
      {{ post.likesCount || 0 }} likes
    </div>

    <!-- Caption -->
    <div class="text-sm mb-1">
      <a [routerLink]="'/profile/' + post.authorId" class="font-semibold mr-2">
        {{ author?.username || 'user' }}
      </a>
      <span>{{ post.caption }}</span>
    </div>

    <!-- Comments Link -->
    <a *ngIf="post.commentsCount > 0" [routerLink]="'/post/' + post.id" class="text-gray-500 text-sm mb-1 block">
      View all {{ post.commentsCount }} comments
    </a>

    <!-- Timestamp -->
    <div class="text-gray-500 text-[10px] uppercase tracking-wide mt-2">
      {{ timeAgo }}
    </div>
  </div>
</div>

// react_backup/src_react/components/ui/PostCard.tsx
import { Link } from 'react-router-dom';
import { Heart, MessageCircle, Send, Bookmark, MoreHorizontal } from 'lucide-react';
import { useEffect, useState } from 'react';
import { formatDistanceToNow } from 'date-fns';
import { getUserData } from '../../lib/userCache';

export const PostCard = ({ post }: { post: any }) => {
  const [author, setAuthor] = useState<any>(null);

  useEffect(() => {
    const fetchAuthor = async () => {
      if (!post.authorId) return;
      const data = await getUserData(post.authorId);
      if (data) {
        setAuthor(data);
      }
    };
    fetchAuthor();
  }, [post.authorId]);

  return (
    <div className="bg-white dark:bg-black border-b border-gray-200 dark:border-gray-800 md:border md:rounded-sm md:mb-6 max-w-lg mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between p-3">
        <Link to={`/profile/${post.authorId}`} className="flex items-center space-x-3">
          <img
            src={author?.photoURL || `https://api.dicebear.com/7.x/avataaars/svg?seed=${post.authorId}`}
            alt={author?.username || 'User'}
            className="w-8 h-8 rounded-full object-cover border border-gray-200 dark:border-gray-800"
          />
          <span className="font-semibold text-sm">{author?.username || 'loading...'}</span>
        </Link>
        <button className="p-1">
          <MoreHorizontal size={20} />
        </button>
      </div>

      {/* Image */}
      <div className="relative w-full bg-gray-100 dark:bg-gray-900 flex items-center justify-center min-h-[300px]">
        <img
          src={post.imageUrl}
          alt={post.caption || 'Post'}
          className="w-full h-auto max-h-[600px] object-contain"
          loading="lazy"
        />
      </div>

      {/* Actions */}
      <div className="p-3">
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center space-x-4">
            <button className="hover:text-gray-500 transition-colors">
              <Heart size={24} className="stroke-[1.5px]" />
            </button>
            <Link to={`/post/${post.id}`} className="hover:text-gray-500 transition-colors">
              <MessageCircle size={24} className="stroke-[1.5px]" />
            </Link>
            <button className="hover:text-gray-500 transition-colors">
              <Send size={24} className="stroke-[1.5px]" />
            </button>
          </div>
          <button className="hover:text-gray-500 transition-colors">
            <Bookmark size={24} className="stroke-[1.5px]" />
          </button>
        </div>

        {/* Likes */}
        <div className="font-semibold text-sm mb-1">
          {post.likesCount || 0} likes
        </div>

        {/* Caption */}
        <div className="text-sm mb-1">
          <Link to={`/profile/${post.authorId}`} className="font-semibold mr-2">
            {author?.username || 'user'}
          </Link>
          <span>{post.caption}</span>
        </div>

        {/* Comments Link */}
        {(post.commentsCount > 0) && (
          <Link to={`/post/${post.id}`} className="text-gray-500 text-sm mb-1 block">
            View all {post.commentsCount} comments
          </Link>
        )}

        {/* Timestamp */}
        <div className="text-gray-500 text-[10px] uppercase tracking-wide mt-2">
          {post.createdAt?.toDate ? formatDistanceToNow(post.createdAt.toDate(), { addSuffix: true }) : 'Just now'}
        </div>
      </div>
    </div>
  );
};
