// prism-angular/src/app/components/layout/layout.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { NavbarComponent } from './navbar.component';

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [RouterOutlet, NavbarComponent],
  templateUrl: './layout.component.html',
})
export class LayoutComponent {}

<div class="min-h-screen bg-white dark:bg-black text-black dark:text-white transition-colors duration-300 flex flex-col md:flex-row">
  <app-navbar></app-navbar>
  <main class="flex-1 pb-16 md:pb-0 md:ml-64 min-h-screen w-full">
    <router-outlet></router-outlet>
  </main>
</div>

// src/components/layout/Layout.tsx
import { Outlet } from 'react-router-dom';
import { Navbar } from './Navbar';

export const Layout = () => {
  return (
    <div className="min-h-screen bg-white dark:bg-black text-black dark:text-white transition-colors duration-300 flex flex-col md:flex-row">
      <Navbar />
      <main className="flex-1 pb-16 md:pb-0 md:ml-64 min-h-screen w-full">
        <Outlet />
      </main>
    </div>
  );
};
