// react_backup/src_react/pages/Home.tsx
import { useEffect, useState, useCallback, useRef } from 'react';
import { PostCard } from '../components/ui/PostCard';
import { getPosts } from '../lib/db';
import { motion } from 'motion/react';

export const Home = () => {
  const [posts, setPosts] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadingMore, setLoadingMore] = useState(false);
  const [lastDoc, setLastDoc] = useState<any>(null);
  const [hasMore, setHasMore] = useState(true);

  const loadMorePosts = useCallback(async () => {
    if (loadingMore || !hasMore || !lastDoc) return;
    
    try {
      setLoadingMore(true);
      const data = await getPosts(lastDoc);
      
      if (data.posts.length === 0) {
        setHasMore(false);
      } else {
        setPosts(prev => [...prev, ...data.posts]);
        setLastDoc(data.lastDoc);
        setHasMore(!!data.lastDoc);
      }
    } catch (error) {
      console.error('Error loading more posts:', error);
    } finally {
      setLoadingMore(false);
    }
  }, [loadingMore, hasMore, lastDoc]);

  const observer = useRef<IntersectionObserver | null>(null);
  
  const lastPostElementRef = useCallback((node: HTMLDivElement | null) => {
    if (loadingMore) return;
    if (observer.current) observer.current.disconnect();
    
    observer.current = new IntersectionObserver(entries => {
      if (entries[0].isIntersecting && hasMore) {
        loadMorePosts();
      }
    });
    
    if (node) observer.current.observe(node);
  }, [loadingMore, hasMore, loadMorePosts]);

  const fetchInitialPosts = async () => {
    try {
      setLoading(true);
      const data = await getPosts();
      setPosts(data.posts);
      setLastDoc(data.lastDoc);
      setHasMore(!!data.lastDoc);
    } catch (error) {
      console.error('Error fetching posts:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchInitialPosts();
  }, []);

  if (loading) {
    return (
      <div className="flex justify-center items-center h-[60vh]">
        <div className="w-12 h-12 border-4 border-purple-500 border-t-transparent rounded-full animate-spin"></div>
      </div>
    );
  }

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="max-w-xl mx-auto pt-4 md:pt-8"
    >
      <div className="flex flex-col space-y-4 md:space-y-6">
        {posts.map((post, index) => {
          const isLast = index === posts.length - 1;
          return (
            <div key={post.id} ref={isLast ? lastPostElementRef : null}>
              <PostCard post={post} />
            </div>
          );
        })}
      </div>
      {loadingMore && (
        <div className="flex justify-center py-6">
          <div className="w-8 h-8 border-4 border-purple-500 border-t-transparent rounded-full animate-spin"></div>
        </div>
      )}
    </motion.div>
  );
};

// prism-angular/src/app/pages/home/home.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PostCardComponent } from '../../components/ui/post-card.component';
import { MasonryGridComponent } from '../../components/ui/masonry-grid.component';
import { DbService } from '../../services/db.service';
import { animate, style, transition, trigger } from '@angular/animations';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule, PostCardComponent, MasonryGridComponent],
  templateUrl: './home.component.html',
  animations: [
    trigger('fadeIn', [
      transition(':enter', [
        style({ opacity: 0 }),
        animate('300ms', style({ opacity: 1 }))
      ])
    ])
  ]
})
export class HomeComponent implements OnInit {
  posts: any[] = [];
  loading = true;
  loadingMore = false;
  lastDoc: any = null;
  hasMore = true;

  constructor(private dbService: DbService) {}

  ngOnInit() {
    this.fetchInitialPosts();
  }

  async fetchInitialPosts() {
    try {
      this.loading = true;
      const data = await this.dbService.getPosts();
      this.posts = data.posts;
      this.lastDoc = data.lastDoc;
      this.hasMore = !!data.lastDoc;
    } catch (error) {
      console.error('Error fetching posts:', error);
    } finally {
      this.loading = false;
    }
  }

  async loadMorePosts() {
    if (this.loadingMore || !this.hasMore || !this.lastDoc) return;
    
    try {
      this.loadingMore = true;
      const data = await this.dbService.getPosts(this.lastDoc);
      
      if (data.posts.length === 0) {
        this.hasMore = false;
      } else {
        this.posts = [...this.posts, ...data.posts];
        this.lastDoc = data.lastDoc;
        this.hasMore = !!data.lastDoc;
      }
    } catch (error) {
      console.error('Error loading more posts:', error);
    } finally {
      this.loadingMore = false;
    }
  }
}

<div *ngIf="loading" class="flex justify-center items-center h-[60vh]">
  <div class="w-12 h-12 border-4 border-purple-500 border-t-transparent rounded-full animate-spin"></div>
</div>

<div *ngIf="!loading" @fadeIn class="max-w-xl mx-auto pt-4 md:pt-8 w-full block">
  <div class="flex flex-col space-y-4 md:space-y-6">
    <div *ngFor="let post of posts; let i = index">
      <app-post-card [post]="post"></app-post-card>
    </div>
  </div>
  
  <!-- Observer element to trigger loading more -->
  <app-masonry-grid 
    class="hidden" 
    [posts]="[]" 
    [hasMore]="hasMore" 
    [loadingMore]="loadingMore" 
    (loadMore)="loadMorePosts()">
  </app-masonry-grid>

  <div *ngIf="loadingMore" class="flex justify-center py-6">
    <div class="w-8 h-8 border-4 border-purple-500 border-t-transparent rounded-full animate-spin"></div>
  </div>
</div>
